### ISSUE TITLE
Using jsonp with reqwest

### ISSUE THREAD

**Issue by cartochris** [AstunTechnology/osgis-ol3-leaflet#3]
Hi

I am trying to see if I can get feature info for my WMS layer using jsonp (to avoid cross origin problems, to note I have set up jsonp to be allowed through GeoServer) but am not entirely sure if I have coded it correctly.

Taking the example, I have changed the 'INFO_FORMAT' and 'type' options to 'text/javascript' and 'jsonp' respectively but am getting the following error in my console log:

Uncaught ReferenceError: parseResponse is not defined
Uncaught TypeError: Cannot read property 'responseText' of undefined

It says in the instructions for the GeoJSON layer that a callback parameter must be specified; I have tried to use the examples from Reqwest but am not getting very far.

What additional parameters must I set when using jsonp? Do I need a success function?

Thanks

**Comment by walkermatt** [comment]
I actually started out using JSONP for the WMS GetFeatureInfo before changing over to use CORS.

Try looking at [this commit](https://github.com/AstunTechnology/osgis-ol3-leaflet/commit/84b891b5020b540efd4879e8c14211cdfaf93d0a#diff-feeaba13318ebdf1717d9c71854f83c5R97) which shows how to specify the `INFO_FORMAT` and `format_options` parameters for GeoServer when calling `getGetFeatureInfoUrl` on the WMS layer source.

**Comment by cartochris** [comment]
That's brilliant thanks so much for the quick response and pointing me in the right direction Matt!
